#!/usr/bin/env python

import rospy
import rospkg
import numpy as np

from rospy.exceptions import ROSInterruptException

class ClassifierNode:

    def __init__(self):
        filepath = rospy.get_param('~file_name', 'classifier.pkl')

if __name__ == '__main__':
    rospy.init_node('classifier_node')

    try:
        classifier_node = ClassifierNode()
        
        rospy.loginfo('Classifier node initialized')
        rospy.spin()
    except rospy.ROSInterruptException:
        pass