#!/usr/bin/env python

import rospy
from rospy.core import parse_rosrpc_uri
from team6_navigate_map.srv import Classify
from sensor_msgs.msg import CompressedImage

class ImageNode:

	def __init__(self):
		self.image_subscriber = rospy.Subscriber('/raspicam_node/image/compressed', CompressedImage, self.ImageCallback)
		
		print('Waiting for classifier service to come up...')
		rospy.wait_for_service('/classifier_node/classify')
		
		self.classify_client = rospy.ServiceProxy('/classifier_node/classify', Classify)

	def ImageCallback(self, image):
		# TODO: process image and extract features
		pass


if __name__=="__main__":
	rospy.init_node('image_node', anonymous=False)
	
	try:
		image_node = ImageNode()

		rospy.loginfo('Image node initialized')
		rospy.spin()
	except rospy.ROSInterruptException:
		pass	