#!/usr/bin/env python

############################################################
# navigate_map node: moves the turtle bot to waypoints 
# while navigating through map 
############################################################

import sys
import rospy

from geometry_msgs.msg import PoseStamped, Point, Quaternion
from actionlib_msgs.msg import GoalStatusArray, GoalStatus

class Navigation:
	def __init__(self, waypoints):
		self.move_base_pub = rospy.Publisher("/move_base_simple/goal", PoseStamped, queue_size=1)
			
		self.waypoints = waypoints
		self.move_base_pub.publish(self._SetHeader(self.waypoints.GetCurrent()))

		self.goal_status = GoalStatus(status=GoalStatus.SUCCEEDED)
		self.status_sub = rospy.Subscriber("/move_base/status", GoalStatusArray, self.CheckStatus)

		# if goal was reached previously, wait for status reset
		while (self.goal_status==GoalStatus.SUCCEEDED):
			rospy.sleep(0.25)
		self.NavWaypoints()

	def _SetHeader(self, pose_stamped):
		pose_stamped.header.stamp = rospy.Time.now()
		pose_stamped.header.frame_id = "map"
		return pose_stamped

	def CheckStatus(self, data):
		try:
			self.goal_status = data.status_list[0]
		except IndexError:
			pass

	def NavWaypoints(self):
		while (self.waypoints.len()):
			if self.goal_status.status == GoalStatus.SUCCEEDED:
				rospy.sleep(2)
				if self.waypoints.PopCurrent():
					self.move_base_pub.publish(self._SetHeader(self.waypoints.GetCurrent()))
				else:
					continue		
			else:
				rospy.sleep(0.5)
				rospy.loginfo(self.goal_status)

			print(self.waypoints.GetCurrent())

class Waypoints:
	def __init__(self, file_path):
		self.waypoints = []
		self.Parse(file_path)

	def __str__(self):
		return str(self.waypoints)

	def len(self):
		return len(self.waypoints)

	def Parse(self, file_path):
		with open(file_path) as file:
			lines = file.readlines()

		file.close()
		for line in lines:
			point = [float(x) for x in line.split(',')]
			waypoint = PoseStamped()
			
			pos = Point(point[0], point[1], point[2])
			orient = Quaternion(point[3], point[4], point[5], point[6])

			waypoint.pose.position, waypoint.pose.orientation = pos, orient
			self.waypoints.append(waypoint)

	def GetCurrent(self):
		return self.waypoints[0]

	def PopCurrent(self):
		self.waypoints.pop(0)
		return self.len()

if __name__=="__main__":
	rospy.init_node('navigate_map', anonymous=False)
	
	# waypoints file path passed via command line/launch file
	file_path = sys.argv[1]
	waypoints = Waypoints(file_path)

	try:
		nav = Navigation(waypoints)
	except rospy.ROSInterruptException:
		pass