#!/usr/bin/env python

############################################################
# navigate_map node: moves the turtle bot to waypoints 
# while navigating through map 
############################################################

import sys
import rospy
import actionlib

from move_base_msgs.msg import MoveBaseAction, MoveBaseGoal
from geometry_msgs.msg import PoseStamped, Point, Quaternion
from actionlib_msgs.msg import GoalStatusArray, GoalStatus

class Navigation:
	def __init__(self, waypoints):
		self.move_base = actionlib.SimpleActionClient('move_base', MoveBaseAction)
		self.move_base.wait_for_server()
			
		self.waypoints = waypoints
		self.NavWaypoints()

	def _SetHeader(self, goal):
		goal.target_pose.header.stamp = rospy.Time.now()
		goal.target_pose.header.frame_id = "map"
		return goal

	def CheckStatus(self, data):
		try:
			self.goal_status = data.status_list[0]
		except IndexError:
			pass

	def NavWaypoints(self):
		while (self.waypoints.len()):
			# get next waypoint and set header 
			current_waypoint = self._SetHeader(self.waypoints.GetCurrent())
			rospy.loginfo("Current Goal:")
			rospy.loginfo(current_waypoint)

			self.move_base.send_goal(current_waypoint)

			success = self.move_base.wait_for_result(rospy.Duration(60))
			state = self.move_base.get_state()

			if success and state == GoalStatus.SUCCEEDED:
				rospy.loginfo(self.move_base.get_goal_status_text)
				rospy.sleep(2)
				self.waypoints.PopCurrent()
			else:
				rospy.loginfo(self.move_base.get_goal_status_text)
				self.move_base.cancel_goal()
				rospy.logerr("Did not reach goal... exiting")
				continue

class Waypoints:
	def __init__(self, file_path):
		# array of MoveBaseGoal waypoints
		self.waypoints = []
		self.Parse(file_path)

	def __str__(self):
		return str(self.waypoints)

	def len(self):
		return len(self.waypoints)

	def Parse(self, file_path):
		with open(file_path) as file:
			lines = file.readlines()

		file.close()
		for line in lines:
			point = [float(x) for x in line.split(',')]
			waypoint = PoseStamped()
			
			pos = Point(point[0], point[1], point[2])
			orient = Quaternion(point[3], point[4], point[5], point[6])

			waypoint.pose.position, waypoint.pose.orientation = pos, orient
			self.waypoints.append(MoveBaseGoal(target_pose=waypoint))

	def GetCurrent(self):
		return self.waypoints[0]

	def PopCurrent(self):
		self.waypoints.pop(0)
		return self.len()

if __name__=="__main__":
	rospy.init_node('navigate_map', anonymous=False)
	
	# waypoints file path passed via command line/launch file
	file_path = sys.argv[1]
	waypoints = Waypoints(file_path)

	try:
		nav = Navigation(waypoints)
	except rospy.ROSInterruptException:
		pass